name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release_bin:
    name: Release Installer
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: hash
        run: |
          echo "pack: ${{ hashFiles('package.json') }}"
          echo "ts: ${{ hashFiles('src/**/*.ts') }}"
          echo "yl: ${{ hashFiles('yarn.lock') }}"
          echo "file: ${{ hashFiles('src/index.ts') }}"
          echo "any: ${{ hashFiles('src/index.*s') }}"
          echo "any2: ${{ hashFiles('src/index.*s*') }}"
          echo "any3: ${{ hashFiles('src/index.t?sx?') }}"
          echo "any4: ${{ hashFiles('src/index.(t?sx?)') }}"
          echo "any5: ${{ hashFiles('src/index.(t?sx?|.pdf)') }}"
