name: Deploy to Prod

on:
  workflow_dispatch:

permissions:
  contents: write # Allows pushing to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and full commit history

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Attempt to merge master into prod
        id: merge_master_to_prod
        run: |
          git checkout prod
          if ! git merge origin/master --no-ff; then
            echo "merge_failed=true" >> $GITHUB_ENV
          fi

      - name: Check merge conflict and sync prod to master if needed
        if: env.merge_failed == 'true'
        run: |
          echo "Conflict detected; syncing prod to master first."
          git checkout master
          if ! git merge origin/prod --no-ff; then
            echo "Manual conflict resolution required on prod to master sync."
            exit 1
          fi
          git push origin master

      - name: Retry merge master to prod after syncing
        if: env.merge_failed == 'true'
        run: |
          git checkout prod
          if ! git merge origin/master --no-ff; then
            echo "Manual conflict resolution required on final master to prod merge."
            exit 1
          fi
          git push origin prod

      - name: Final merge attempt if no conflict initially
        if: env.merge_failed != 'true'
        run: |
          git push origin prod
