name: CI
on:
  workflow_call:
    inputs:
      branchOrCommit:
        description: 'Branch/Commit/Tag'
        required: false
        type: string
        default: 'master'
      skip:
        description: 'Skip'
        required: false
        type: string
        default: 'false'

jobs:
  format:
    if: github.event_name != 'workflow_call' || inputs.skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - run: echo "Type ${{ github.event_name }}"
      - run: echo "Skip ${{ inputs.skip }}"
      - run: echo "Skip ${{ inputs.branchOrCommit }}"

  lint:
    if: github.event_name != 'workflow_call' || inputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI"
      - run: sleep 10
