name: Deploy Table staging

on:
  workflow_dispatch:
    inputs:
      branchOrCommit:
        description: 'Branch or commit SHA to deploy'
        required: false
        type: string
      skipDeploy:
        description: 'Skip deployment to ECS'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-tables-api-staging:
    runs-on: ubuntu-latest

    env:
      SELECTED_REF: ${{ inputs.branchOrCommit != '' && inputs.branchOrCommit || github.sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branchOrCommit }}

      - name: Determine Commit SHA
        id: determine-sha
        run: |
          echo ${{ inputs.branchOrCommit }}

      - name: Prepare Commit Message
        run: |
          echo "SHORT_CURRENT_COMMIT=$(echo '${{ env.SHA }}' | cut -c1-7)" >> $GITHUB_ENV
          echo "SHORT_MASTER_COMMIT=$(echo '${{ env.SHA }}' | cut -c1-7)" >> $GITHUB_ENV
        env:
          SHA: ${{ github.sha }}

      - name: Prepare Commit Message
        run: |
          echo 'auto(cloud): Updating Skynet Images from ${{ env.SHORT_CURRENT_COMMIT }} to ${{ env.SHORT_MASTER_COMMIT }}'
