name: Deploy to Prod

on:
  workflow_dispatch:

permissions:
  contents: write # Allows pushing to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and full commit history

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes on prod not in master
        run: |
          # Get diff of changes between prod and master
          git checkout prod
          git diff --name-only master..prod > changes_in_prod.txt

      - name: Apply changes from prod to master if any
        if: ${{ steps.check-for-changes.outputs.has_changes }}
        run: |
          # Only apply changes if there are any
          if [ -s changes_in_prod.txt ]; then
            echo "Applying changes from prod to master"
            git checkout master
            git checkout prod -- $(cat changes_in_prod.txt)
            git commit -m "Sync changes from prod to master"
            git push origin master
          fi

      - name: Merge master into prod
        run: |
          git checkout prod
          git merge origin/master --no-ff
          git push origin prod
