name: Merge Master to Prod

on:
  workflow_dispatch: # Triggered manually

jobs:
  merge-master-to-prod:
    name: Merge Master into Prod
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for pushing commits

    steps:
      # Checkout the `prod` branch
      - name: Checkout Prod Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: prod

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Attempt to Merge Master into Prod
      - name: Merge Master into Prod
        id: merge-master-to-prod
        run: |
          git fetch origin master
          git merge --no-ff origin/master -m "Deploy Staging to Production" || exit 1

      # If Merge Fails, Sync Prod to Master and Retry
      - name: Handle Merge Conflict
        if: failure()
        run: |
          echo "Merge from master to prod failed. Syncing prod to master and retrying..."
          git checkout master
          git pull origin master
          git merge --no-ff origin/prod -m "Merge prod into master [skip ci]"
          git push origin master

          echo "Retrying merge from master to prod..."
          git checkout prod
          git merge --no-ff origin/master -m "Merge master into prod [skip ci]"
          git push origin prod

      # Validate Final Sync
      - name: Validate Sync
        run: |
          git fetch origin prod
          if ! git merge-base --is-ancestor origin/master origin/prod; then
            echo "Prod is still not fully updated with master. Manual resolution required."
            exit 1
          else
            echo "Prod is successfully updated with master."
          fi
