name: Deploy to Prod

on:
  workflow_dispatch:

permissions:
  contents: write # Allows pushing to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and full commit history

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge master into prod
        id: merge_master_into_prod
        run: |
          git checkout prod
          if ! git merge origin/master --no-ff; then
            echo "Merge conflict detected when merging master into prod."
            exit 1
          fi
          git push origin prod

      - name: Merge prod back to master to sync changes
        if: steps.merge_master_into_prod.outcome == 'failure'
        run: |
          git checkout master
          if git merge origin/prod --no-ff; then
            git push origin master
            echo "Successfully merged prod back into master to resolve conflicts."
          else
            echo "Manual conflict resolution required for prod to master merge."
            exit 1
          fi

      - name: Retry Merge master into prod after sync
        if: steps.merge_master_into_prod.outcome == 'failure'
        run: |
          git checkout prod
          if git merge origin/master --no-ff; then
            git push origin prod
            echo "Successfully re-merged master into prod after syncing prod to master."
          else
            echo "Manual conflict resolution required for master to prod merge."
            exit 1
          fi
