name: Deploy Test Production

on:
  push:
    branches:
      - prod
    paths:
      - 'src/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-sauron-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
