name: Trigger All Workflows

on:
  workflow_dispatch:
    inputs:
      skipDeploy:
        description: 'Skip deployment to ECS (only updates the image)'
        required: false
        type: boolean
        default: false
      branchOrCommit:
        description: 'Branch or commit SHA to deploy'
        required: false
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest

    env:
      SELECTED_REF: ${{ inputs.branchOrCommit != '' && inputs.branchOrCommit || github.sha }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SELECTED_REF }}

      - name: Trigger Workflow 1
        run: |
          gh workflow run deploytest.yml \
           --ref ${{ env.SELECTED_REF }} \
           --field skipDeploy=${{ inputs.skipDeploy }} \
           --field branchOrCommit=${{ env.SELECTED_REF }}
