name: Trigger All Workflows

on:
  workflow_dispatch:
    inputs:
      branchOrCommit:
        description: 'Branch or commit SHA to deploy'
        required: false
        type: string
      skipDeploy:
        description: 'Skip deployment to ECS'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest

    env:
      SELECTED_REF: ${{ inputs.branchOrCommit != '' && inputs.branchOrCommit || github.sha }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_PREFIX: prod-

    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SELECTED_REF }}

      - name: Create and push new date-based tag
        run: |
          new_tag="prod-$(date -u '+%Y-%m-%d_%H-%M')"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$new_tag" ${{ env.SELECTED_REF }}
          git push origin "$new_tag"

      - name: Trigger Workflow 1
        run: |
          gh workflow run deploytest.yml \
           --ref master \
           --field skipDeploy=${{ inputs.skipDeploy }} \
           --field branchOrCommit=${{ env.SELECTED_REF }}
