name: Trigger All Workflows

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow 1
        run: |
          gh workflow run deploytest.yml

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
