name: Trigger All Workflows

on:
  workflow_dispatch:
    inputs:
      skipDeploy:
        description: 'Skip deployment to ECS (only updates the image)'
        required: false
        type: boolean
        default: false
      branchOrCommit:
        description: 'Branch or commit SHA to deploy'
        required: false
        type: string
        default: master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branchOrCommit }}

      - name: Trigger Workflow 1
        run: |
          gh workflow run deploytest.yml \
           --ref ${{ inputs.branchOrCommit }} \
           --field skipDeploy=${{ inputs.skipDeploy }} \
           --field branchOrCommit=${{ inputs.branchOrCommit }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
