name: Deploy Cloud New

on:
  workflow_dispatch:
    inputs:
      branchOrCommit:
        description: 'Branch/Commit/Tag'
        required: false
        type: string
        default: 'master'
      skip_ci:
        description: 'Skip CI and deploy directly'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  GIT_REF: ${{ github.event_name == 'workflow_dispatch' && inputs.branchOrCommit || github.sha }}

concurrency: deploy-cloud-staging

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      branchOrCommit: ${{ inputs.branchOrCommit || github.sha }}
      skip: ${{ inputs.skip_ci }}

  deploy-staging:
    needs: ci
    if: needs.ci.result == 'success' || needs.ci.result == 'skipped'
    uses: ./.github/workflows/deploy-workspace.yml

  check-staging:
    needs: deploy-staging
    if: needs.deploy-staging.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check staging"

  cancel-stack:
    needs: deploy-staging
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cancelling stack"
